sudo: required

dist: trusty

language: php

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.phpbrew
    - $HOME/.npm

before_install:
  - |
    git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)' || {
      echo "Only docs were updated, stopping build process."
      exit
    }
  - nvm install && nvm use
  - npm install npm -g

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      env:
        WP_VERSION=latest
        CI_RUN=e2e
      cache:
        yarn: true
      script:
        - ./bin/run-e2e-tests.sh || exit 1
